import { Camera, Check, Dumbbell, HeartPulse, Scale, Sparkles, Target } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Logo, PrimaryButton } from './components'
import { useApp } from '../state/app-context'
import { calculateNutritionTargets, type ActivityLevel, type BiologicalSex, type Macros, type UserProfile } from '../domain/nutrition'

const goals = [
  { name: 'Ganancia muscular', description: 'Aumenta tu ingesta y controla especialmente proteína y calorías.', icon: Dumbbell },
  { name: 'Mantener peso', description: 'Controla tu alimentación manteniendo un consumo equilibrado.', icon: Scale },
  { name: 'Reducir peso', description: 'Haz seguimiento de tu consumo respecto a tus objetivos.', icon: Target },
  { name: 'Mejorar alimentación', description: 'Conoce mejor la composición de tus comidas.', icon: HeartPulse },
] as const

export function WelcomePage() { const navigate = useNavigate(); return <section className="welcome-page"><Logo /><div className="welcome-visual"><div className="scan-orbit"><Camera size={35} /><i /></div><span className="visual-food food-a">🥑</span><span className="visual-food food-b">🍅</span><span className="visual-food food-c">🥦</span><div className="visual-plate">⌁</div></div><div className="welcome-copy"><p className="eyebrow"><Sparkles size={15} /> Nutrición inteligente</p><h1>Tu alimentación,<br /><em>vista</em> de forma inteligente.</h1><p>Fotografía tus comidas y obtén una estimación de sus calorías, macronutrientes y composición.</p></div><div className="features"><span><Check size={14} />Reconoce alimentos</span><span><Check size={14} />Estima porciones</span><span><Check size={14} />Calcula macros</span></div><PrimaryButton onClick={() => navigate('/profile-setup')}>Comenzar</PrimaryButton></section> }

export function ProfileSetupPage() {
  const { profile, setProfile, userGoal, applyPersonalization } = useApp(); const navigate = useNavigate()
  const update = <K extends keyof UserProfile>(field: K, value: UserProfile[K]) => setProfile({ ...profile, [field]: value })
  return <section className="standard-page profile-setup"><p className="step">Personalización · 1 de 2</p><h1>Conozcámonos mejor</h1><p className="intro">Usaremos estos datos para generar metas diarias orientativas.</p><section className="target-panel profile-form"><h2>Tu información</h2><div className="target-grid"><label>Edad<span><input aria-label="Edad" min="14" max="100" type="number" value={profile.age} onChange={(event) => update('age', Number(event.target.value))} />años</span></label><label>Peso<span><input aria-label="Peso" min="30" max="300" type="number" value={profile.weight} onChange={(event) => update('weight', Number(event.target.value))} />kg</span></label><label className="wide-field">Estatura<span><input aria-label="Estatura" min="120" max="230" type="number" value={profile.height} onChange={(event) => update('height', Number(event.target.value))} />cm</span></label></div><label>Sexo biológico<select aria-label="Sexo biológico" value={profile.biologicalSex} onChange={(event) => update('biologicalSex', event.target.value as BiologicalSex)}><option value="female">Mujer</option><option value="male">Hombre</option></select></label><label>Nivel de actividad<select aria-label="Nivel de actividad" value={profile.activityLevel} onChange={(event) => update('activityLevel', event.target.value as ActivityLevel)}><option value="sedentary">Sedentario · poco movimiento</option><option value="light">Ligero · 1 a 3 días por semana</option><option value="moderate">Moderado · 3 a 5 días por semana</option><option value="high">Alto · 6 a 7 días por semana</option></select></label></section><p className="guidance-note">Estimación orientativa para esta demostración; no sustituye el consejo de un profesional de salud.</p><PrimaryButton onClick={() => { applyPersonalization(profile, userGoal); navigate('/goal') }}>Continuar</PrimaryButton></section>
}

export function GoalPage() {
  const { userGoal, setUserGoal, profile, targets, setTargets } = useApp(); const navigate = useNavigate()
  const updateTarget = (field: keyof Macros, value: string) => setTargets({ ...targets, [field]: Number(value) || 0 })
  return <section className="standard-page goal-page"><p className="step">Personalización · 2 de 2</p><h1>¿Cuál es tu objetivo?</h1><p className="intro">Generamos metas según tu perfil. Puedes ajustarlas antes de continuar.</p><div className="goal-list">{goals.map(({ name, description, icon: Icon }) => <button key={name} className={`goal-option ${userGoal === name ? 'selected' : ''}`} onClick={() => { setUserGoal(name); setTargets(calculateNutritionTargets(profile, name)) }}><span><Icon size={20} /></span><div><b>{name}</b><p>{description}</p></div>{userGoal === name && <Check size={18} />}</button>)}</div><section className="target-panel"><h2>Objetivos diarios estimados</h2><div className="target-grid">{([['calories', 'Calorías', 'kcal'], ['protein', 'Proteína', 'g'], ['carbs', 'Carbohidratos', 'g'], ['fats', 'Grasas', 'g']] as const).map(([field, label, unit]) => <label key={field}>{label}<span><input aria-label={label} type="number" value={targets[field]} onChange={(event) => updateTarget(field, event.target.value)} />{unit}</span></label>)}</div></section><p className="guidance-note">Metas calculadas de forma orientativa y editables para la demostración.</p><PrimaryButton onClick={() => navigate('/home')}>Continuar</PrimaryButton></section>
}
